"""Pure V3-M1 handoff contracts for R23, R30, and R25.

Importing this package performs no historical factory import, response run,
JSON write, or V3 authority issuance.
"""

from .contracts import (
    ADAPTER_COMMITMENT_RECEIPT_SCHEMA_VERSION,
    ADAPTER_CONTRACT_MAX_ANCESTRY_COMMITS,
    ADAPTER_CONTRACT_MAX_BLOB_ENTRIES,
    ADAPTER_CONTRACT_MAX_PROVENANCE_ANCESTRY,
    ADAPTER_CONTRACT_MAX_ROOTS,
    ADAPTER_CONTRACT_MAX_SOURCE_BYTES,
    ADAPTER_CONTRACT_MAX_TEXT_BYTES,
    ADAPTER_CONTRACT_MAX_WIRE_BYTES,
    ADAPTER_CONTRACT_WIRE_SCHEMA_VERSION,
    ADAPTER_IDS,
    ADAPTER_MULTISTEP_CERTIFICATE_SCHEMA_VERSION,
    ADAPTER_ONE_STEP_CERTIFICATE_SCHEMA_VERSION,
    AdapterCommitmentReceipt,
    AdapterContract,
    adapter_commitment_receipt_from_wire,
    adapter_commitment_receipt_payload,
    adapter_commitment_receipt_sha,
    adapter_commitment_receipt_to_wire,
    adapter_contract_from_wire,
    adapter_contract_payload,
    adapter_contract_sha,
    adapter_contract_to_wire,
    adapter_source_path,
    all_adapter_contracts,
    classify_adapter_ancestry,
    get_adapter_contract,
    validate_adapter_commitment_receipt,
    verify_adapter_contract,
    verify_adapter_source,
)
from .r23 import R23_ADAPTER_CONTRACT, get_r23_adapter_contract
from .r25 import R25_ADAPTER_CONTRACT, get_r25_adapter_contract
from .r30 import R30_ADAPTER_CONTRACT, get_r30_adapter_contract


__all__ = [
    "ADAPTER_COMMITMENT_RECEIPT_SCHEMA_VERSION",
    "ADAPTER_CONTRACT_MAX_ANCESTRY_COMMITS",
    "ADAPTER_CONTRACT_MAX_BLOB_ENTRIES",
    "ADAPTER_CONTRACT_MAX_PROVENANCE_ANCESTRY",
    "ADAPTER_CONTRACT_MAX_ROOTS",
    "ADAPTER_CONTRACT_MAX_SOURCE_BYTES",
    "ADAPTER_CONTRACT_MAX_TEXT_BYTES",
    "ADAPTER_CONTRACT_MAX_WIRE_BYTES",
    "ADAPTER_CONTRACT_WIRE_SCHEMA_VERSION",
    "ADAPTER_IDS",
    "ADAPTER_MULTISTEP_CERTIFICATE_SCHEMA_VERSION",
    "ADAPTER_ONE_STEP_CERTIFICATE_SCHEMA_VERSION",
    "AdapterCommitmentReceipt",
    "AdapterContract",
    "R23_ADAPTER_CONTRACT",
    "R25_ADAPTER_CONTRACT",
    "R30_ADAPTER_CONTRACT",
    "adapter_commitment_receipt_from_wire",
    "adapter_commitment_receipt_payload",
    "adapter_commitment_receipt_sha",
    "adapter_commitment_receipt_to_wire",
    "adapter_contract_from_wire",
    "adapter_contract_payload",
    "adapter_contract_sha",
    "adapter_contract_to_wire",
    "adapter_source_path",
    "all_adapter_contracts",
    "classify_adapter_ancestry",
    "get_adapter_contract",
    "get_r23_adapter_contract",
    "get_r25_adapter_contract",
    "get_r30_adapter_contract",
    "validate_adapter_commitment_receipt",
    "verify_adapter_contract",
    "verify_adapter_source",
]
